# Generated by Django 5.2.7 on 2025-10-27 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monitoring", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="monitoringalert",
            name="analysis_result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="monitoring.analysisresult",
            ),
        ),
        migrations.AddField(
            model_name="monitoringalert",
            name="recipients",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="monitoringconfiguration",
            name="pipeline",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monitoring_config",
                to="monitoring.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="pipelinesegment",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="segments",
                to="monitoring.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="satelliteimage",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="satellite_images",
                to="monitoring.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="satellite_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_results",
                to="monitoring.satelliteimage",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["-created_at"], name="monitoring__created_ac9d4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["user"], name="monitoring__user_id_debfb4_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["action"], name="monitoring__action_a5517e_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["resource_type"], name="monitoring__resourc_48023d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pipelinesegment",
            unique_together={("pipeline", "segment_number")},
        ),
        migrations.AlterUniqueTogether(
            name="satelliteimage",
            unique_together={("pipeline", "image_date", "satellite_name")},
        ),
    ]
