# Generated by Django 5.2.7 on 2025-10-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_satelliteimage_uploaded_by_satelliteimage_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="theme",
        ),
    ]
