# Generated by Django 5.2.7 on 2025-10-28 12:17

import monitoring.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="satelliteimage",
            name="image_file",
            field=models.FileField(
                help_text="Satellite image file in TIFF format (.tif, .tiff). Maximum size: 100 MB",
                upload_to="satellite_images/",
                validators=[monitoring.validators.validate_tiff_file],
            ),
        ),
        migrations.AlterField(
            model_name="satelliteimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail image (JPG, PNG, or TIFF). Maximum size: 5 MB",
                null=True,
                upload_to="thumbnails/",
                validators=[monitoring.validators.validate_thumbnail_file],
            ),
        ),
    ]
