# Generated by Django 5.2.7 on 2025-10-31 12:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_remove_systemsettings_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="default_bounds",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True,
                help_text="Automatically calculated satellite image bounds from route",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("auto", "Auto")],
                default="light",
                max_length=10,
            ),
        ),
    ]
